--  This file is part of the eliona project.
--  Copyright © 2022 LEICOM iTEC AG. All Rights Reserved.
--  Authors: Adam Lange, et al.
--  ______ _ _
-- |  ____| (_)
-- | |__  | |_  ___  _ __   __ _
-- |  __| | | |/ _ \| '_ \ / _` |
-- | |____| | | (_) | | | | (_| |
-- |______|_|_|\___/|_| |_|\__,_|
--
--  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
--  BUT NOT LIMITED  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
--  NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
--  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
--  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

-- Patch scripts (database/patches/*.sql) are generally executed in alphabetical order when the app starts within
-- an eliona environment. If the app starts for the first time, the patch scripts runs after the initialisation
-- script (database/init.sql). So changes on data and data structure can be done, although the app is
-- already installed and initialized (the database/init.sql is already executed). To signal that the
-- patch is already installed, you have to register the patch with versioning.register_patch(). Afterwards
-- the eliona environment skips execution for the corresponding patch file.

-- begin;
--     -- do something for the patch
--
--     -- Register the patch prevents the eliona environment to start the script a second time.
--     -- For registered patches the environment skips the execution for the corresponding patch file.
--     select versioning.register_patch('010100', null, null, 'weather');
-- commit;
